# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ml.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x08ml.proto\"\x16\n\x05Image\x12\r\n\x05image\x18\x01 \x01(\t\"a\n\x07\x43lasses\x12&\n\x07\x63lasses\x18\x01 \x03(\x0b\x32\x15.Classes.ClassesEntry\x1a.\n\x0c\x43lassesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32*\n\x0b\x43\x61rDetector\x12\x1b\n\x07predict\x12\x06.Image\x1a\x08.Classesb\x06proto3'
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='Image.image', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=12,
  serialized_end=34,
)


_CLASSES_CLASSESENTRY = _descriptor.Descriptor(
  name='ClassesEntry',
  full_name='Classes.ClassesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Classes.ClassesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Classes.ClassesEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=133,
)

_CLASSES = _descriptor.Descriptor(
  name='Classes',
  full_name='Classes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='classes', full_name='Classes.classes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CLASSES_CLASSESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=133,
)

_CLASSES_CLASSESENTRY.containing_type = _CLASSES
_CLASSES.fields_by_name['classes'].message_type = _CLASSES_CLASSESENTRY
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['Classes'] = _CLASSES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'ml_pb2'
  # @@protoc_insertion_point(class_scope:Image)
  })
_sym_db.RegisterMessage(Image)

Classes = _reflection.GeneratedProtocolMessageType('Classes', (_message.Message,), {

  'ClassesEntry' : _reflection.GeneratedProtocolMessageType('ClassesEntry', (_message.Message,), {
    'DESCRIPTOR' : _CLASSES_CLASSESENTRY,
    '__module__' : 'ml_pb2'
    # @@protoc_insertion_point(class_scope:Classes.ClassesEntry)
    })
  ,
  'DESCRIPTOR' : _CLASSES,
  '__module__' : 'ml_pb2'
  # @@protoc_insertion_point(class_scope:Classes)
  })
_sym_db.RegisterMessage(Classes)
_sym_db.RegisterMessage(Classes.ClassesEntry)


_CLASSES_CLASSESENTRY._options = None

_CARDETECTOR = _descriptor.ServiceDescriptor(
  name='CarDetector',
  full_name='CarDetector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=135,
  serialized_end=177,
  methods=[
  _descriptor.MethodDescriptor(
    name='predict',
    full_name='CarDetector.predict',
    index=0,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_CLASSES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CARDETECTOR)

DESCRIPTOR.services_by_name['CarDetector'] = _CARDETECTOR

# @@protoc_insertion_point(module_scope)
